variable "name" {}
variable "cidr" {}
variable "allowed_cidr_ranges" {}
variable "allowed_access_groups" {}
variable "dns_servers" {}
variable "organization_name" {}
variable "tags" {}
variable "logs_retention" {}
variable "authentication_type" {}
variable "split_tunnel" {}
variable "enable_self_service_portal" {}
variable "transport_protocol" {}