global:
  region: "asia-southeast1"
  state_bucket: "nasir-elk-tf-state"
  project_id: "nasir-456515"

network:
  vpc_name: "nasir-elk-vpc" 
  auto_create_subnetworks: false
  description: "Nasir ELK VPC"
  subnet_name: "nasir-elk-asia-southeast1"
  subnet_ip: "10.1.0.0/16"
  subnet_description: "Nasir ELK asia southeast 1"

vm:
  app: 
    instance_name: "app-vm"
    zone: "asia-southeast1-b"
    instance: "linux"
    instance_type: "n1-standard-1"
    disk_size_gb: 50
    disk_type: "pd-balanced"
    image: "ubuntu-os-cloud/ubuntu-2204-lts"
    create_internal_static_ip: true
    create_external_static_ip: true
    allow_stopping_for_update: true  
  elk: 
    instance_name: "elk-vm"
    zone: "asia-southeast1-c"
    instance: "linux"
    instance_type: "n1-standard-1"
    disk_size_gb: 50
    disk_type: "pd-balanced"
    image: "ubuntu-os-cloud/ubuntu-2204-lts"
    create_internal_static_ip: true
    create_external_static_ip: true
    allow_stopping_for_update: true    

firewall-ssh:
  name: "nasir-elk-vpc-allow-ssh"
  description: "allow ssh"
  protocol: "tcp"
  ports: ["22"]
  source_ranges: ["0.0.0.0/0"]
  target_tags: ["app", "elk"]  




