global:
  region: "ap-southeast-1"
  state_bucket: "data-engineering-spotify-analysis"

network:
  vpc_name: "data-engineering-spotify-analysis-vpc" 
  description: "data-engineering-spotify-analysis-vpc"
  cidr_block: "10.0.0.0/16"
  instance_tenancy: "default"
  enable_dns_support: true
  enable_dns_hostnames: true
  subnet_count: 2
  subnet_mask: "24"

ec2:
  kafka: 
    instance_name: "kafka"
    instance_type: "t3.micro"
    ami: "ami-0c1907b6d738188e5"
    root_block_device:
      volume_size : 50
      volume_type: "gp3"
      delete_on_termination: true
      encrypted: true
      
 


