global:
  region: "ap-southeast-1"
  state_bucket: "data-engineering-spotify-analysis"

network:
  vpc_name: "data-engineering-spotify-analysis-vpc" 
  description: "data-engineering-spotify-analysis-vpc"
  cidr_block: "10.0.0.0/16"
  instance_tenancy: "default"
  enable_dns_support: true
  enable_dns_hostnames: true
  subnet_count: 2
  subnet_mask: "24"

vm:
  app: 
    instance_name: "app-vm"
    zone: "asia-southeast1-b"
    instance: "linux"
    instance_type: "n1-standard-1"
    disk_size_gb: 50
    disk_type: "pd-balanced"
    image: "ubuntu-os-cloud/ubuntu-2204-lts"
    create_internal_static_ip: true
    create_external_static_ip: true
    allow_stopping_for_update: true  
  elk: 
    instance_name: "elk-vm"
    zone: "asia-southeast1-c"
    instance: "linux"
    instance_type: "n2-standard-2"
    disk_size_gb: 50
    disk_type: "pd-balanced"
    image: "ubuntu-os-cloud/ubuntu-2204-lts"
    create_internal_static_ip: true
    create_external_static_ip: true
    allow_stopping_for_update: true    

firewall-ssh:
  name: "nasir-elk-vpc-allow-ssh"
  description: "allow ssh"
  protocol: "tcp"
  ports: ["22"]
  source_ranges: ["0.0.0.0/0"]
  target_tags: ["app", "elk"]  




